### ISSUE TITLE
Pending cap show market id

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-blue-subgraph#10]
When querying the pending caps the id is the concatenation of the market params. I think it would be better if it was the the id of the market instead

<img width="1271" alt="Screenshot 2024-02-12 at 16 59 55" src="https://github.com/morpho-org/morpho-blue-subgraph/assets/44097430/4cb4ab78-e74f-4f32-953e-719b106cbfb9">

**Comment by julien-devatom** [comment]
`id` must be unique for a pending cap, but you can retrieve the market id by doing the following query:
```graphql
{
  pendingCaps(first: 1) {
    metaMorphoMarket {
      market {
        id
      }
    }
  }
}
```

**Comment by julien-devatom** [comment]
Better, you can do that:
```graphql
{
  metaMorphos(first: 10) {
    
    markets {
      market {
        id
      }
       pendingCaps {
        validAt
        isNewMarket
        cap
        status
      }
    }
  }
}
```
